name: a4_safe_pulse
description: Accident Detection and Emergency Alert App
publish_to: "none"

version: 1.0.0+1

environment:
 sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  #Animation (hourglass loading)

  lottie: ^3.1.0
  
  #Save user data locally

  shared_preferences: ^2.2.2
  
  #Time formatting

  intl: ^0.20.2
  audioplayers: ^5.2.1
  #Language support

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ambulance.jpeg
    - assets/images/app_logo.jpeg
    - assets/animations/hourglass.json
    - assets/sounds/alarm.mpeg